version: '3.8'
services:
  react-pixi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app/react-pixi
    ports:
      - '3000:3000'
    tty: true
